// Generated by CoffeeScript 1.4.0
var loadTweets, slogans;

slogans = [["DA UN'IDEA A UN'IMPRESA", "slogan-idea-impresa.php"], ["RIPOSIZIONARE UN'AZIENDA", "slogan-riposizionare-azienda.php"], ["LA DIFESA DI UN PATRIMONIO", "slogan-difesa-patrimonio.php"], ["ASSISTERE UN DISABILE", "slogan-assistere-disabile.php"], ["GESTISCI LA TUA VITA", "slogan-gestisci-vita.php"]];

loadTweets = function(user, count) {
  var api, items;
  items = [];
  api = "https://api.twitter.com/1/statuses/user_timeline/" + user + ".json?count=" + count;
  console.log(api);
  $.ajax({
    dataType: "jsonp",
    url: api,
    success: function(data) {
      var el, _fn, _i, _len, _results;
      _fn = function(el) {};
      _results = [];
      for (_i = 0, _len = data.length; _i < _len; _i++) {
        el = data[_i];
        _fn(el);
        items.push(el);
        _results.push(console.log(el));
      }
      return _results;
    }
  });
  return items;
};

$(function() {
  $('#maximage').maximage({
    cycleOptions: {
      after: function(curr, next, opts) {
        $("#slogan h1").html("<a href ='" + slogans[opts.currSlide][1] + "'>" + slogans[opts.currSlide][0] + "&nbsp;<i class='icon-circle-arrow-right'></i></a>");
      }
    }
  });
  loadTweets('avvocatwit', 5);
});
